name: simple-tester

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.7]

    steps:
    - uses: actions/checkout@v2
    - name: Use simple-tester ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
      env:
        CI: true
